---
apiVersion: v1
kind: Namespace
metadata:
  name: ctse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management-deployment
  namespace: ctse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-management
  template:
    metadata:
      labels:
        app: customer-management
    spec:
      containers:
        - name: customer-management
          image: it19140544/ecommerce-customers:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: customer-management-config
---
