apiVersion: v1
kind: Service
metadata:
  namespace: ctse
  name: customer-management-service
spec:
  selector:
    app: customer-management
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: LoadBalancer
  publishNotReadyAddresses: true
